In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [100]:
# Create 2 4x6 matrices of random numbers.
# Use a for loop  to compute dot products between corresponding columns

matrix1 = np.random.randint(low=0, high=10, size=(4, 4)) 
matrix2 = np.random.randint(low=0, high=10, size=(4, 4))
print('Matrix 1: \n', matrix1)
print()
print('Matrix 2: \n', matrix2)
print()
print(matrix1.shape)
print(matrix2.shape)
print(type(matrix1))

    #for row, col in matrix1, matrix2:
    #   result = result + matrix1[row][col]*matrix2[row][col]
print(range(len(matrix1)))
print(range(len(matrix2[0])))
print()

result_matrix = [[0 for i in range(6)] for j in range(4)]
print('result matrix', type(result_matrix))
print()

# Iterating by row of matrix1
for i in range(len(matrix1)):
        
    # Iterating by column of matrix2
    for j in range(len(matrix2[0])):
            
        # Iterating by rows of matrix 2
        for k in range(len(matrix2)):
            result += matrix1[i][k] * matrix2[k][j]
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]
                
#return result
print(result_matrix)
print()
print(result)
matrix1 = np.array(np.squeeze(np.asarray(matrix1)))
matrix2 = np.array(np.squeeze(np.asarray(matrix2)))
#matrix1 = list(matrix1)
#matrix2 = list(matrix2)
#print(matrix1)
#print(matrix2)

print('dot product of matrix1 and matrix2: \n', np.dot(matrix1, matrix2))


Matrix 1: 
 [[2 0 7 5]
 [9 6 7 8]
 [9 0 7 5]
 [5 8 5 6]]

Matrix 2: 
 [[6 3 4 5]
 [2 6 4 4]
 [3 7 5 9]
 [1 2 2 6]]

(4, 4)
(4, 4)
<class 'numpy.ndarray'>
range(0, 4)
range(0, 4)

result matrix <class 'list'>

[[38, 65, 53, 103, 0, 0], [95, 128, 111, 180, 0, 0], [80, 86, 81, 138, 0, 0], [67, 110, 89, 138, 0, 0]]

76722
dot product of matrix1 and matrix2: 
 [[ 38  65  53 103]
 [ 95 128 111 180]
 [ 80  86  81 138]
 [ 67 110  89 138]]


In [89]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [103]:
# Is Orthogonal?
a = np.array([16, -2, 4]) 
b = np.array([0.5, 2, -1]) 
np.dot(a,b)

0.0

In [132]:
# Test whether the dot product sign is invariant to 
# scalar multiplication

# Generate two vectors (R3) - R3 just means 3 elements
vector1 = np.array([-3, 4, 6])
vector2 = np.array([3, 6, -3])
print('v1:',vector1)
print('v2:',vector2)

# Generate two scalars
scalar1 = 2
scalar2 = 3

# Compute the dot product between vectors
print('dot product:',np.dot(vector1,vector2))

# Compute the dot product between the scaled vectors
vector1 = scalar1*vector1
vector2 = scalar2*vector2
print('dot product w/scalars:',np.dot(vector1,vector2))

v1: [-3  4  6]
v2: [ 3  6 -3]
dot product: -3
dot product w/scalars: -18


In [142]:
# Is the dot product commutative; which means is: A*B = B*A?
# This is true for algebra, but is this true for vectors?
# Definitely not the case for matrix multiplication.
# a'*B == b'*a

# 1) Generate two 100-element random row vectors, compute dot product a with b, b with a
v1 = np.random.randint(low=0, high=10, size=(100))
v2 = np.random.randint(low=0, high=10, size=(100))
print('dot product (v1*v2):',np.dot(v1,v2))
print('dot product (v2*v1):',np.dot(v2,v1))

# 2) Generate two 2-element integer row vectors, repeat
v1 = np.random.randint(low=0, high=10, size=(2))
v2 = np.random.randint(low=0, high=10, size=(2))
print(v1)
print(v2)

dot product (v1*v2): 2054
dot product (v2*v1): 2054
[2 9]
[1 0]


In [168]:
# Create two random-integer vectors (R4)
v1 = np.random.randint(low=0, high=10, size=(4))
v2 = np.random.randint(low=0, high=10, size=(4))
print('v1:',v1)
print('v2:',v2)

# Compute the lengths of the individual vectors, and magnitude of their dot product
# Length (?)
v1m = np.sqrt(np.dot(v1,v1))
v2m = np.sqrt(np.dot(v2,v2))
print('v1m:',v1m)
print('v2m:',v2m)
# Dot product magnitude (DPM) correct?
dpm = sum(np.multiply(v1, v2)) # Hadamard multiplication
print('dpm:',dpm)

# "Normalize" the vectors (create unit vectors along the same directions)
v1u = v1/v1m
v2u = v2/v2m
print('v1u:',v1u)
print('v2u:',v2u)

v1m = np.sqrt(np.dot(v1u,v1u)) #proof, should be 1
v2m = np.sqrt(np.dot(v2u,v2u))
print('v1m(u):',v1m)
print('v2m(u):',v2m)

# Compute the magnitude of that dot product correct?
dpum = sum(np.multiply(v1u, v2u))
print('dpum:',dpum)

v1: [8 9 6 2]
v2: [3 1 4 5]
v1m: 13.601470508735444
v2m: 7.14142842854285
dpm: 67
v1u: [0.5881717  0.66169316 0.44112877 0.14704292]
v2u: [0.42008403 0.14002801 0.56011203 0.70014004]
v1m(u): 0.9999999999999999
v2m(u): 0.9999999999999999
dpum: 0.6897692831787727
