In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import *
import scipy.io as sio
from mpl_toolkits.mplot3d import Axes3D

In [20]:
# Generate random data (design matrix X, data y)
# Solve for beta using QR decomp.
# Compare the QR results against the "standard" left-inverse method.

m = 10
n = 3
X = np.array( np.random.randn(m,n) )
y = np.array( np.random.randn(m,1) )
Q, R = np.linalg.qr(X)

# Method 1: Beta = (RTR)^-1 x (QR)^T x y <- QR decomposition
RT = np.transpose(R)
RTRi = np.linalg.inv(np.dot(RT, R))
QR = np.dot(Q, R)
QRT = np.transpose(QR)
#B1 = RTRi * QRT * y
B1 = np.dot(RTRi, QRT)
B1 = np.dot(B1, y)
print("B1:\n", B1)
print()

# Method 2: Beta = (XTX)^-1 x (XT * y <- left inverse
XT = np.transpose(X)
XTXi = np.linalg.inv(np.dot(XT, X))
B2 = np.dot(XTXi, XT)
B2 = np.dot(B2, y)

print("B2:\n", B2)
print()
print("X:\n", X)
print("Q:\n", Q)
print("R:\n", R)
print()

B1:
 [[-0.08099725]
 [-0.67912865]
 [-0.08170933]]

B2:
 [[-0.08099725]
 [-0.67912865]
 [-0.08170933]]

X:
 [[ 0.61603707  0.81906931 -1.54520795]
 [ 0.51951983  0.18496687  0.96690184]
 [ 0.32440427 -0.112715   -1.82870799]
 [ 0.38856614  0.40492932  0.61003039]
 [-0.90016434 -1.08427277  0.27973987]
 [-0.9979506   0.69866386 -0.52520672]
 [ 0.50726875 -1.43843594  0.75280595]
 [-0.19274561  0.5359036  -1.15055652]
 [-1.06427616  1.38798122  0.34986272]
 [-0.9777568   3.04032483 -0.54053641]]
Q:
 [[-0.27291988 -0.37854994 -0.39517199]
 [-0.23016032 -0.17602619  0.39338467]
 [-0.14371923 -0.04529541 -0.61749239]
 [-0.17214455 -0.20714211  0.28448477]
 [ 0.39879539  0.5212699  -0.09178245]
 [ 0.44211716  0.03969002 -0.18105977]
 [-0.22473279  0.28657035  0.14059302]
 [ 0.08539114 -0.10587028 -0.35245512]
 [ 0.47150105 -0.13971001  0.19095832]
 [ 0.4331708  -0.62817802  0.07208618]]
R:
 [[-2.25720848  1.89730857 -0.10027277]
 [ 0.         -3.53158832  1.12439731]
 [ 0.          0.       