In [1]:
import numpy as np
from sympy import *
import matplotlib.pyplot as plt

In [3]:
# 101. Code challenge: Implement the MCA algorithm!

#MCA algorithm in code!!!

# Compute the inverse using inv(), compare to your implementation of the MCA

# Create matrix
a = np.array([[1,3,0], [0,-2,8], [7,2,-6]])
m = a
m == a
det = np.linalg.det(a)
print(a)
print()
print('determinant:',round(det))
print()

# Create matrix of determinants
for i in range(len(a)): # rows
    # define rows and columns for submatrix
    for j in range(len(a)): # cols
        atemp = np.delete(a, i, 0) # delete row
        atemp = np.delete(atemp, j, 1) # delete col
        dets = np.linalg.det(atemp)
        m[i,j] = round(dets)
        print('i',i)
        print('j',j)
        print(atemp)
        print()

print(m)


[[ 1  3  0]
 [ 0 -2  8]
 [ 7  2 -6]]

determinant: 164.0

i 0
j 0
[[-2  8]
 [ 2 -6]]

i 0
j 1
[[ 0  8]
 [ 7 -6]]

i 0
j 2
[[ 0 -2]
 [ 7  2]]

i 1
j 0
[[-56  14]
 [  2  -6]]

i 1
j 1
[[-4 14]
 [ 7 -6]]

i 1
j 2
[[ -4 -56]
 [  7   2]]

i 2
j 0
[[-56  14]
 [-74 384]]

i 2
j 1
[[ -4  14]
 [308 384]]

i 2
j 2
[[ -4 -56]
 [308 -74]]

[[    -4    -56     14]
 [   308    -74    384]
 [-20468  -5848  17544]]


In [195]:
# Create array of matching size to original of alternating +'s and -'s 
b = np.array([[1,-1,1], [-1,1,-1], [1,-1,1]])
print(b)
print()

# Perform Hadamard multiplication (e.g. element wise) of alternating +/- matrix with matrix of determinants
c = np.multiply(m,b)
print(c)
print()
c_t = np.transpose(c)
print(c_t)
print()
ainv = c_t / 164
print(ainv)

[[ 1 -1  1]
 [-1  1 -1]
 [ 1 -1  1]]

[[-4 56 14]
 [18 -6 19]
 [24 -8 -2]]

[[-4 18 24]
 [56 -6 -8]
 [14 19 -2]]

[[-0.02439024  0.1097561   0.14634146]
 [ 0.34146341 -0.03658537 -0.04878049]
 [ 0.08536585  0.11585366 -0.01219512]]


In [225]:
# original matrix x inverse matrix should result in identity matrix

#result = np.multiply(ainv,a) #ainv*a
#result = ainv*a
result = np.dot(a,ainv)
result = np.around(result)
result2 = np.linalg.inv(a)
result3 = ainv - result2

print('original matrix:\n',a)
print()
print('inverse matrix:\n', ainv)
print()
print('inverse matrix 2:\n',result2)
print()
print('subtraction of the two inverse matrices:\n',result3)
print()
print('shouuld result in identity matrix:\n', result)


original matrix:
 [[ 1  3  0]
 [ 0 -2  8]
 [ 7  2 -6]]

inverse matrix:
 [[-0.02439024  0.1097561   0.14634146]
 [ 0.34146341 -0.03658537 -0.04878049]
 [ 0.08536585  0.11585366 -0.01219512]]

inverse matrix 2:
 [[-0.02439024  0.1097561   0.14634146]
 [ 0.34146341 -0.03658537 -0.04878049]
 [ 0.08536585  0.11585366 -0.01219512]]

subtraction of the two inverse matrices:
 [[ 3.46944695e-18  1.38777878e-17  0.00000000e+00]
 [ 0.00000000e+00 -6.93889390e-18 -6.93889390e-18]
 [ 1.38777878e-17  1.38777878e-17 -1.73472348e-18]]

shouuld result in identity matrix:
 [[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [15]:
# 103. Code challenge: inverse of a diagonal matrix

# Create some diagonal matrices, start with 2x2 integers, work up to larger matrices
# Compute their inverses (what is the condition on the diagonal matrix for invertibility)
# ...Think...

a = np.array([[2, 0], [0, 3]])
a3 = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])
print(a)
print()
print(a3)
print()

print('rank of a:', np.linalg.matrix_rank(a))
print('rank of a3:', np.linalg.matrix_rank(a3))

ainv = np.linalg.inv(a)
a3inv = np.linalg.inv(a3)
print('inv of a:\n', ainv)
print()
print('inv of a3:\n', a3inv)

[[2 0]
 [0 3]]

[[2 0 0]
 [0 3 0]
 [0 0 4]]

rank of a: 2
rank of a3: 3
inv of a:
 [[0.5        0.        ]
 [0.         0.33333333]]

inv of a3:
 [[0.5        0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.25      ]]


In [57]:
# 108. Code challenge: psuedoinverse of invertible matrices

# Psuedoinverse is the same as the "real" inverse for an invertible matrix?

m = 5
a = np.array( np.random.randn(m,m) )
print('original matrix\n',a)
print()
print('rank of a:', np.linalg.matrix_rank(a))
print()

ainv = np.linalg.inv(a)
print('ainv\n',ainv)
print()

apinv = np.linalg.pinv(a)
print('painv\n',apinv)
print()

i = np.around(a.dot(ainv), 0)
print(i)
print()

ip = np.around(a.dot(apinv), 0)
print(ip)
print()

print(np.around(ainv - apinv))

original matrix
 [[ 1.74219658 -0.56650194 -0.50926325  0.51203767  0.61402984]
 [ 2.13607667  1.79527764  0.93329791 -1.11586733  0.64085133]
 [-0.00503701  0.14502126  1.17538259  1.43657902  1.75656251]
 [-0.02458007  1.20219322 -0.39238081 -0.5497334   0.22696471]
 [ 0.89171618 -1.36891545 -1.01540825  0.77910557 -2.80330631]]

rank of a: 5

ainv
 [[ 0.26034193  0.21625768 -0.01076978 -0.09409941  0.09209543]
 [-0.21939159  0.0857723   0.33272807  0.84292731  0.24828778]
 [-0.44653665  0.35096632  0.14280307 -0.73790671  0.01216212]
 [-0.03106212 -0.12875604  0.60585205  0.54589437  0.38758847]
 [ 0.34305776 -0.13600483 -0.04924931 -0.02255204 -0.34535619]]

painv
 [[ 0.26034193  0.21625768 -0.01076978 -0.09409941  0.09209543]
 [-0.21939159  0.0857723   0.33272807  0.84292731  0.24828778]
 [-0.44653665  0.35096632  0.14280307 -0.73790671  0.01216212]
 [-0.03106212 -0.12875604  0.60585205  0.54589437  0.38758847]
 [ 0.34305776 -0.13600483 -0.04924931 -0.02255204 -0.34535619]]

[[ 1.