In [ ]:
# Section 5: Matrix Rank

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [23]:
# 65. Code challenge: reduced-rank matrix via multiplication

# Create reduced-rank matrices using matrix multiplication
# make a matrix
m = 8
n = 47
r = 7

# create a random matrix
A = np.random.randn(m,r)

ra = np.linalg.matrix_rank(A)
print('rank=' + str(ra))

B = np.random.randn(r,n)


# Create 10x10 matrix with rank=4 (use matrix multiplication)
C = np.dot(A, B)
ra_C = np.linalg.matrix_rank(C)
print('rank=' + str(ra_C))
print(C.shape)

# Generalize the procedure to create MxN matrix with rank r.
# This was done between lines 5 through 15

rank=7
rank=7
(8, 47)


In [103]:
# 66. Code challenge: scalar multiplication and rank

# Test whether the matrix rank is invariant to scalar multiplication
# rank(A) != rank(1*A)
# Create two matrices: full-rank and a reduced-rank (random)
# Create some sclalar
# PRint ranks of F, R, l*F, l*R
# Check whether rank(l8F) == 1*rank(F)

m = 6
n = 4
######
s = 25438439489230

# create a random matrix
#F = np.dot(np.random.randn(m,n), np.random.randn(n))
F = np.random.randn(m,n)*np.random.randn(n)
F = F*s
R = np.dot(np.random.randn(m,n-1),np.random.randn(n-1,n))
R = R*s

ra_F = np.linalg.matrix_rank(F)
ra_R = np.linalg.matrix_rank(R)

print('rank=' + str(ra_F))
print(F.shape)
print('rank=' + str(ra_R))
print(R.shape)

rank=4
(6, 4)
rank=3
(6, 4)


In [ ]:
# 66. Code challenge: scalar multiplication and rank

# Test whether the matrix rank is invariant to scalar multiplication
# rank(A) != rank(1*A)
# Create two matrices: full-rank and a reduced-rank (random)
# Create some sclalar
# PRint ranks of F, R, l*F, l*R
# Check whether rank(l8F) == 1*rank(F)

m = 6
n = 4
######
o = 10
p = 9

r1 = 7
r2 = 3

s = 1

# create a random matrix
F = np.dot(A, B)np.random.randn(m,n)*np.random.randn(n)
R = np.random.randn(m,n-1)*np.random.randn(n-1,n)

ra_F = np.linalg.matrix_rank(F)
ra_R = np.linalg.matrix_rank(R)

print('rank=' + str(ra_F))
print(F.shape)
print('rank=' + str(ra_R))
print(R.shape)

In [147]:
# 68. Code challenge: rank of multiplied and summed matrices

# rules: rank of AB<=min (rank(A), rank(B))
#        rank of A+B<=rank(A) + rank(B)
# Generate two matrices (A and B), 2x5
# Compute AtA and BtB
# find their ranks
# find ranks of AtA + BtB

m = 2
n = 5

A = np.random.randn(m,n)
B = np.random.randn(m,n)
print('A:\n', A)
print()
print('B:\n', B)
print()
ra = np.linalg.matrix_rank(A)
rb = np.linalg.matrix_rank(B)
print('rank=' + str(ra))
print('rank=' + str(rb))
print()

AtA = np.matrix(A.transpose())
BtB = np.matrix(B.transpose())
print('AtA:\n', AtA)
print()
print('BtB:\n', BtB)
print()
rata = np.linalg.matrix_rank(AtA)
rbtb = np.linalg.matrix_rank(BtB)
print('rank=' + str(rata))
print('rank=' + str(rbtb))
print()

#AtAx = np.matrix(A) * AtA
#BtBx = np.matrix(B) * BtB
AtAx = np.matrix(np.dot(A, AtA))
BtBx = np.matrix(np.dot(B, BtB))
print('AtAx:\n', AtAx)
print()
print('BtBx:\n', BtBx)
AtBt = np.dot(AtAx, BtBx)
rAtBt = np.linalg.matrix_rank(AtBt)
print('rank=' + str(rAtBt))
rAtAx = np.linalg.matrix_rank(AtAx)
print('rank=' + str(rAtAx))
rBtBx = np.linalg.matrix_rank(BtBx)
print('rank=' + str(rBtBx))
print()

AtpBt = AtAx + BtBx
#AtpBt = np.matrix(AtAx) + np.matrix(BtBx)
print('AtpBt:\n', AtpBt)
rAtpBt = np.linalg.matrix_rank(AtAx+BtBx)
print('rank=' + str(rAtpBt))
print()

rank_plus = np.linalg.matrix_rank(AtAx.astype(np.float64) + BtBx.astype(np.float64))
print('rank_plus:', rank_plus)
print()

import scipy.stats as ss
rank_ss = max(ss.rankdata(AtAx+BtBx))
print(rank_ss)
print()


A:
 [[-1.05289061  0.81449269  0.05618034  0.68076983  1.29229106]
 [-1.80062847  0.05568901 -0.81892645 -2.44495075 -0.16182942]]

B:
 [[ 0.53462053 -0.5951723   0.31193448  0.64530508  1.21470519]
 [-0.51370276  0.09402063 -0.40272588 -0.88879135  0.69122529]]

rank=2
rank=2

AtA:
 [[-1.05289061 -1.80062847]
 [ 0.81449269  0.05568901]
 [ 0.05618034 -0.81892645]
 [ 0.68076983 -2.44495075]
 [ 1.29229106 -0.16182942]]

BtB:
 [[ 0.53462053 -0.51370276]
 [-0.5951723   0.09402063]
 [ 0.31193448 -0.40272588]
 [ 0.64530508 -0.88879135]
 [ 1.21470519  0.69122529]]

rank=2
rank=2

AtAx:
 [[3.90859693 0.02163611]
 [0.02163611 9.91997759]]

BtBx:
 [[ 2.62927963 -0.19012522]
 [-0.19012522  1.702661  ]]
rank=2
rank=2
rank=2

AtpBt:
 [[ 6.53787656 -0.16848911]
 [-0.16848911 11.62263859]]
rank=2

rank_plus: 2

4.0



In [162]:
# This comes up in real world problems, such as statistics problems. "Is some vector contained in the column space of 
# some matrix, which means in the span of some set of vectors?"

# Determine whether this vector
    #v = [1, 2, 3, 4]' the ' means to transform into a column vector
# is in the span of these sets
    #s = [ [4,3,6,2]T, [0,4,0,1]T ] we are thinking about this matrix as a set of column vectors
    #T = [ [1,2,2,2]T, [0,0,1,2]T ]
    
# Key here is to use the rank
    
v = [1,2,3,4]
S = np.matrix([ [4,3,6,2], [0,4,0,1]])
T = np.matrix([ [1,2,2,2], [0,0,1,2]])
S = S.transpose()
T = T.transpose()
print('S:\n', S)
print('T:\n', T)
print()

S_rank = np.linalg.matrix_rank(S)
T_rank = np.linalg.matrix_rank(T)
print('S_rank:', S_rank)
print('T_rank:', T_rank)
print()

Saug = np.column_stack((S, v))
Saug_rank = np.linalg.matrix_rank(Saug)
print(Saug)
print('Saug_rank:', Saug_rank)
print()
Taug = np.column_stack((T, v))
Taug_rank = np.linalg.matrix_rank(Taug)
print(Taug)
print('Saug_rank:', Taug_rank)
print()

S:
 [[4 0]
 [3 4]
 [6 0]
 [2 1]]
T:
 [[1 0]
 [2 0]
 [2 1]
 [2 2]]

S_rank: 2
T_rank: 2

[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
Saug_rank: 3

[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]
Saug_rank: 2

